### ISSUE TITLE
Code changes to see improved results

### ISSUE THREAD

**Issue by chowkamlee81** [edwardzhou130/PolarSeg#16]
Kindly let us know changes made to code to improve from 54.0 to 57.2

**Comment by YangZhang4065** [comment]
Hi @chowkamlee81 ,

Thank you for your attention. We improved the results by using leakyrelu and dropblock with little to none additional inference cost. We will release the code this week and I will update you on this issue.

**Comment by edwardzhou130** [comment]
Hi @chowkamlee81,

I have updated the code and the pretrained model. You need to install one new library, [dropblock](https://github.com/miguelvr/dropblock), to run the updated code.

**Comment by chowkamlee81** [comment]
Thanks @edwardzhou130 for updated code. Helped a lot. Closing the issue
