### ISSUE TITLE
Format of output labels for submission to Codalab competition

### ISSUE THREAD

**Issue by DeepakVellampalli** [edwardzhou130/PolarSeg#17]
@edwardzhou130 

Would to like to know the format generated from test_pretrain.py for output labels is the proper format for codalab submission. Your code needs to be modified?

Kindly suggest

**Comment by edwardzhou130** [comment]
Hi @DeepakVellampalli,

Our code saves the label in the training format(continuous label 0-19), while the submission requires the label to be in the original format(discontinuous label 0-259). You can use ``remap_semantic_labels.py``() from [semantic-kitti-api](https://github.com/PRBonn/semantic-kitti-api) to do the inverse transferring.

**Comment by DeepakVellampalli** [comment]
Your solution worked. Thank you very much
