### ISSUE TITLE
Any codes to count parameters/FLOPs of PolarSeg model?

### ISSUE THREAD

**Issue by chowkamlee81** [edwardzhou130/PolarSeg#20]
@edwardzhou130 @YangZhang4065 

Any codes to count parameters/FLOPs of PolarSeg model? Kindly suggest

**Comment by edwardzhou130** [comment]
We used [thop](https://github.com/Lyken17/pytorch-OpCounter) to count the parameters and MACs.

**Comment by chowkamlee81** [comment]
Thanks @edwardzhou130 . Closing the issue
