### ISSUE TITLE
Other dataset support

### ISSUE THREAD

**Issue by tsunghan-mama** [edwardzhou130/PolarSeg#22]
Hi:

Thanks for sharing your excellent work.
As you've mentioned in your paper that you've tested your approaches on three different dataset, including SemanticKITTI, A2D2 and Paris-Lille-3D.
Would you like to provide the program or pre-trained weight on these dataset?
Thanks!

**Comment by edwardzhou130** [comment]
Hi,

Thanks for your interest. I will add code and pretrained models for more datasets soon.
