### ISSUE TITLE
realust visualization

### ISSUE THREAD

**Issue by yangchandler** [edwardzhou130/PolarSeg#24]
Hi,thx for your resource code. 
I have one question,
I used test_pretrain.py to get infer labels,but when I use SemanticKitti-API to visualize the labels,  The visualization results are dark,as if the label does not correspond to the official color.Did you have a question like this?

**Comment by edwardzhou130** [comment]
I did not transfer the label back to the original label format which is used in semantic-kitti-api. So the label probably don't match with the colormap https://github.com/edwardzhou130/PolarSeg/blob/3f95ad6ad97889ae2a233fa774deaf77ec77eb90/semantic-kitti.yaml#L37-L71
You can use remap_semantic_labels.py(with --inverse) from semantic-kitti-api to do the inverse transferring.

**Comment by yangchandler** [comment]
My question has been solved. Thank you for your answer.
