### ISSUE TITLE
Label encoding 

### ISSUE THREAD

**Issue by abhigoku10** [edwardzhou130/PolarSeg#29]
@YangZhang4065 @Xyouz  thanks for sharing the source code , can you please let me know what is the use of functions like 
" SemKITTI2train_single(label):" and "SemKITTI2train(label):" which is used  during training and testing , how Is it modifying the labels during saving

**Comment by Xyouz** [comment]
Before calling the ```SemKitti2train``` function labels range from 0 (which represents points to be ignored) to 25 or so. The ```SemKitti2train``` function shift them by 1 so that they range from 0 to 24 (for the useful classes) and points that are to be ignored get labelled as 255.

**Comment by abhigoku10** [comment]
@Xyouz  for visualization on the nuscenes data what code base should be used ?

**Comment by Xyouz** [comment]
I won't be able to help you on this one as I only worked with the semantickitti data.
