### ISSUE TITLE
nuScenes Pretrained Model Size Mismatch

### ISSUE THREAD

**Issue by n0tva1id** [edwardzhou130/PolarSeg#35]
Hi, authors! When I tried directly run test_pretrain_nuscenes.py, it told me that the loaded model didn't match the defined model.
Here are the command line logs:

> test_pretrain_nuscenes.py
Namespace(data_dir='data', grid_size=[480, 360, 32], model='polar', model_save_path='pretrained_weight/Nuscenes_PolarSeg.pt', test_batch_size=1, test_output_path='out/Nuscenes/lidarseg/test', visibilty=False)
Traceback (most recent call last):
  File "test_pretrain_nuscenes.py", line 196, in <module>
    main(args)
  File "test_pretrain_nuscenes.py", line 75, in main
    my_model.load_state_dict(torch.load(model_save_path))
  File "/home/**/anaconda3/envs/polarseg/lib/python3.6/site-packages/torch/nn/modules/module.py", line 847, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for ptBEVnet:
        size mismatch for BEV_model.network.inc.conv.0.weight: copying a param with shape torch.Size([64]) from checkpoint, the shape in current model is torch.Size([32]).
        size mismatch for BEV_model.network.inc.conv.0.bias: copying a param with shape torch.Size([64]) from checkpoint, the shape in current model is torch.Size([32]).
        size mismatch for BEV_model.network.inc.conv.0.running_mean: copying a param with shape torch.Size([64]) from checkpoint, the shape in current model is torch.Size([32]).
        size mismatch for BEV_model.network.inc.conv.0.running_var: copying a param with shape torch.Size([64]) from checkpoint, the shape in current model is torch.Size([32]).
        size mismatch for BEV_model.network.inc.conv.1.conv1.0.weight: copying a param with shape torch.Size([64, 64, 3, 3]) from checkpoint, the shape in current model is torch.Size([64, 32, 3, 3]).

**Comment by edwardzhou130** [comment]
The nuScenes pretrained model was trained with the visibility feature so that the channel is 64 rather than 32.  It should work after adding the visibility arg ``python test_pretrain_nuscenes.py --visibility``.  There is a typo (``visibility`` --> ``visibilty``) in the code, I'll commit a fix now.

**Comment by qifang804** [comment]
It works. Thank you for helping me out!
