### ISSUE TITLE
Why calculate IoU from voxel label？

### ISSUE THREAD

**Issue by jialeli1** [edwardzhou130/PolarSeg#37]
Hi.

I a new to point cloud segmentation. There are problems that have been bothering me a lot.

1). Why does PolarNet ([here](https://github.com/edwardzhou130/PolarSeg/blob/3531f15bb9f38b3ae075ea33183d32ab6139980a/test_pretrain_SemanticKITTI.py#L119)) calculate IoU from voxel-wise label instead of point-wise label? Even PolarNet directly saves the voxel label to the file for submission ([here](https://github.com/edwardzhou130/PolarSeg/blob/3531f15bb9f38b3ae075ea33183d32ab6139980a/test_pretrain_SemanticKITTI.py#L162)).

2.) As I learned from [semantic-kitti-api](https://github.com/PRBonn/semantic-kitti-api#validation), predictions about each point of the scan are required when submitted to the benchmark. Is my understanding correct? Or is it not necessary to predict the label of every point?

Thank you for answering me. It really bothers me very much.

**Comment by edwardzhou130** [comment]
> 1). Why does PolarNet (here) calculate IoU from voxel-wise label instead of point-wise label? Even PolarNet directly saves the voxel label to the file for submission (here).

In the validation and testing, we will project the voxel-wise label to the point-wise label ([here](https://github.com/edwardzhou130/PolarSeg/blob/3531f15bb9f38b3ae075ea33183d32ab6139980a/test_pretrain_SemanticKITTI.py#L120)). ``predict_labels`` is the predicted voxel-wise label, ``val_grid`` is the voxel location of each point. And there are two reasons why we use the voxel-wise label in the training: 1. it will be faster to train. 2. our experiment showed the result won't be improved if we use the point-wise label.

> 2.) As I learned from semantic-kitti-api, predictions about each point of the scan are required when submitted to the benchmark. Is my understanding correct? Or is it not necessary to predict the label of every point?

Yes. The submission file needs to be the label of every point. And the label needs to be in the original dataset format([here](https://github.com/edwardzhou130/PolarSeg/blob/3531f15bb9f38b3ae075ea33183d32ab6139980a/semantic-kitti.yaml#L144-L164))

**Comment by jialeli1** [comment]
Thank you for your kind reply.

I mistakenly thought that it was mapping val_pt_labs to voxel. I feel much clearer.
