### ISSUE TITLE
What is the visibility features ?

### ISSUE THREAD

**Issue by SofianeB-03** [edwardzhou130/PolarSeg#41]
Hello, thank you very much for your great work ! I have a question: What is the visibility features and what is the advantage to use it ?

**Comment by edwardzhou130** [comment]
The visibility feature is a label generated by ray tracing to the voxel. It has the following three classes:

- visible: The empty place between object and LiDAR sensor. 
- occluded: The place behind the object.
- occupied: the voxel that has point in it.

It is an independent feature of the volume space and can improve the overall performance.

**Comment by SofianeB-03** [comment]
@edwardzhou130 , thank you for rour reply.
