### ISSUE TITLE
about 'ring convolutions' 

### ISSUE THREAD

**Issue by ZhiqingMiao** [edwardzhou130/PolarSeg#46]
@YangZhang4065 @edwardzhou130 Thank you for open sourcing this great repo!
I have a question:
ring convolutions that you mentioned in your paper in section 3.4
where is the implementation of it? Is that here? Just about padding?
Thank you a lot in advance!
https://github.com/edwardzhou130/PolarSeg/blob/3531f15bb9f38b3ae075ea33183d32ab6139980a/network/BEV_Unet.py#L115-L118
感谢开源这个项目，非常棒！
我有个问题，您在论文3.4章中提到的ring convolution， 它的代码实现在哪？
是这里吗？只是在padding的时候有所不同吗？
期待您的回答！感谢！
https://github.com/edwardzhou130/PolarSeg/blob/3531f15bb9f38b3ae075ea33183d32ab6139980a/network/BEV_Unet.py#L115-L118

**Comment by edwardzhou130** [comment]
Yes, it's implemented through circular padding.

**Comment by ZhiqingMiao** [comment]
> Yes, it's implemented through circular padding.

Thank you so much！

**Comment by HolmesShuan** [comment]
Hi, all! As a newbie to 3D Seg, I am curious why **circular padding** is equivalent to Ring-Conv? Thanks in advance. @edwardzhou130 @Carl12138aka

**Comment by YangZhang4065** [comment]
> Hi, all! As a newbie to 3D Seg, I am curious why **circular padding** is equivalent to Ring-Conv? Thanks in advance. @edwardzhou130 @Carl12138aka

Ring-conv is running a standard convolution over a ring-alike feature map. So the problem here is about how to mimic a ring-alike feature map using whatever we have in PyTorch. Circular padding is basically stitching both ends of a normal feature map together by copying & concat the gradient and features from the right side of a feature map to its left side and vice versa. Thus it creates a ring-alike feature map and simulates ring-conv behavior.

**Comment by HolmesShuan** [comment]
Thanks for your quick reply! To be specific, turning
```python
1, 2, 3
4, 5, 6
7, 8, 9
```
into
```python
9, 7, 8, 9, 7
3, 1, 2, 3, 1
6, 4, 5, 6, 4
9, 7, 8, 9, 7
3, 1, 2, 3, 1
```
Is that correct?

**Comment by YangZhang4065** [comment]
> Thanks for your quick reply! To be specific, turning
> 
> ```python
> 1, 2, 3
> 4, 5, 6
> 7, 8, 9
> ```
> 
> into
> 
> ```python
> 9, 7, 8, 9, 7
> 3, 1, 2, 3, 1
> 6, 4, 5, 6, 4
> 9, 7, 8, 9, 7
> 3, 1, 2, 3, 1
> ```
> 
> Is that correct?

There is no circular padding between the top and bottom row because you want to connect the right and left sides (thus forming a ring) but not the top and bottom (near the vehicle and far from the vehicle).
So it is more turning into:
```
3, 1, 2, 3, 1
6, 4, 5, 6, 4
9, 7, 8, 9, 7
```
