### ISSUE TITLE
ValueError : Input must be 1- or 2-d.

### ISSUE THREAD

**Issue by Youngjoo-Kim** [edwardzhou130/PolarSeg#5]
Hi..!
I just do it 'python train.py'  with KITTI Dataset, but the training is wrong..!
What should i do..?

![스크린샷, 2020-04-20 14-36-26](https://user-images.githubusercontent.com/57059989/79717347-5b25a600-8314-11ea-9e25-ee15b7e5b160.png)

**Comment by edwardzhou130** [comment]
Hi Youngjoo,

It probably is because the validation data is missing or the validation part is not working, so that the prediction list is empty.

**Comment by zhaodejian** [comment]
> 你好..！ 我只是用 KITTI 数据集做'python train.py'，但是训练是错误的..！ 我该怎么办..？
> 
> ![스크린샷, 2020-04-20 14-36-26](https://user-images.githubusercontent.com/57059989/79717347-5b25a600-8314-11ea-9e25-ee15b7e5b160.png)

do you solve your problem? how do you solve it?
