### ISSUE TITLE
Error while generating predictions

### ISSUE THREAD

**Issue by varun365** [edwardzhou130/PolarSeg#6]
Hi,
I was trying to test the pretrained polar model

Once the test is completed on validation split ti throws below error while generating predictions

Namespace(data_dir='data', grid_size=[480, 360, 32], model='polar', model_save_path='pretrained_weight/SemKITTI_PolarSeg.pt', test_batch_size=1, test_output_path='out/SemKITTI_test')
********************************************************************************
Test network performance on validation split
********************************************************************************
100%|████████████████████████████████████████████████████████████████████████████████████████████████| 101/101 [00:28<00:00,  4.72it/s]Validation per class iou:
car : 94.93%
bicycle : 17.08%
motorcycle : 0.00%
truck : 0.00%
bus : 0.00%
person : 50.76%
bicyclist : 85.54%
motorcyclist : 0.00%
road : 96.99%
parking : 27.94%
sidewalk : 82.96%
other-ground : 0.00%
building : 66.53%
fence : 19.99%
vegetation : 75.00%
trunk : 57.21%
terrain : 69.88%
pole : 44.73%
traffic-sign : 38.37%
100%|████████████████████████████████████████████████████████████████████████████████████████████████| 101/101 [00:28<00:00,  3.53it/s]
Current val miou is 43.575
Inference time per 1 is 0.0594 seconds

********************************************************************************
Generate predictions for test split
********************************************************************************
0it [00:00, ?it/s]Traceback (most recent call last):
  File "test_pretrain.py", line 191, in <module>
    main(args)
  File "test_pretrain.py", line 170, in main
    del test_grid,test_pt_fea,test_index
UnboundLocalError: local variable 'test_grid' referenced before assignment
0it [00:00, ?it/s]

any changes to be made to generate predictions ?

Thanks in Advance

**Comment by edwardzhou130** [comment]
It seems like the test_dataset is empty. Can you check if the test sequences (11-21) are correctly placed in the ``data`` folder, as instructed in our [README](https://github.com/edwardzhou130/PolarSeg#prepare-dataset-and-environment)?

**Comment by varun365** [comment]
hi @edwardzhou130 
I have place the test sequence files in data
here is the tree directory
.
├── data
│   └── sequences
│       ├── 08
│       │   ├── image_2
│       │   ├── labels
│       │   └── velodyne
│       ├── 11
│       ├── 12
│       ├── 13
│       ├── 14
│       ├── 15
│       ├── 16
│       ├── 17
│       ├── 18
│       ├── 19
│       ├── 20
│       └── 21
├── dataloader
│   └── __pycache__
├── imgs
├── network
│   └── __pycache__
├── pretrained_weight
└── semantic-kitti-api
    ├── auxiliary
    │   └── shaders
    └── config

Still it gives the same error while generating predictions.
