### ISSUE TITLE
How to improve the speed of training process?

### ISSUE THREAD

**Issue by happiensslz** [edwardzhou130/PolarSeg#7]
@edwardzhou130  Thanks for your good work. It takes me about 7 days to train the PolarSeg without loading the pre-trained model.  Can you give me some suggestions to solve it?

**Comment by edwardzhou130** [comment]
To train the PolarSeg faster, the best way is to decrease the grid size for the larger batch size. For example, use grid size [256,256,32] and batch size 4. Though there is no guarantee the performance will be as good as our default setting, the final result will be very close base on our test.

**Comment by happinesslz** [comment]
Thanks for your advice! @edwardzhou130
